delimiter $$

CREATE TABLE `comment` (
  `COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUTHOR` varchar(100) DEFAULT NULL,
  `BODY` varchar(255) DEFAULT NULL,
  `POST_ID` int(11) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `CREATED_DT` date DEFAULT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  KEY `POST_FK` (`POST_ID`),
  CONSTRAINT `POST_FK` FOREIGN KEY (`POST_ID`) REFERENCES `post` (`POST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `post` (
  `POST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) DEFAULT NULL,
  `POST_DATE` date DEFAULT NULL,
  `POST_PART_ID` int(11) DEFAULT NULL,
  `AUTHOR` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `CONTENT_URL` varchar(500) DEFAULT NULL,
  `CREATED_DT` date DEFAULT NULL,
  PRIMARY KEY (`POST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `post_mention` (
  `POST_ID` int(11) NOT NULL,
  `URL` varchar(200) NOT NULL,
  PRIMARY KEY (`POST_ID`,`URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `post_part` (
  `POST_PART_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BODY` varchar(255) DEFAULT NULL,
  `POST_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`POST_PART_ID`),
  KEY `POST_FK2` (`POST_ID`),
  CONSTRAINT `POST_FK2` FOREIGN KEY (`POST_ID`) REFERENCES `post` (`POST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `post_tag` (
  `POST_ID` int(11) DEFAULT NULL,
  `TAG_ID` int(11) DEFAULT NULL,
  KEY `POST_FK3` (`POST_ID`),
  KEY `TAG_FK` (`TAG_ID`),
  CONSTRAINT `POST_FK3` FOREIGN KEY (`POST_ID`) REFERENCES `post` (`POST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `TAG_FK` FOREIGN KEY (`TAG_ID`) REFERENCES `tag` (`TAG_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `tag` (
  `TAG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


